
spring:
  jackson:
    serialization:
      indent-output: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${http://100.3.4.5:8761/eureka}
  instance:
    hostname: ${EUREKA_INSTANCE:localhost}


