
spring:
  jackson:
    serialization:
      indent-output: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://3.108.6.122:8761/eureka}
  instance:
    hostname: ${EUREKA_INSTANCE:3.108.6.122}


