
spring:
  data:
    mongodb:
      uri: ${DB_HOST:mongodb://paras:admin1992@ec2-3-6-37-141.ap-south-1.compute.amazonaws.com/product}
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${ZOOKEEPER_HOST:15.206.189.160:9092}






