
spring:
  data:
    mongodb:
      uri: ${DB_HOST:mongodb://paras:admin@ec2-65-0-89-246.ap-south-1.compute.amazonaws.com/test}
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${ZOOKEEPER_HOST:localhost:9092}


elastic:
  search:
    host-name: ${ELASTIC_SEARCH_HOST:localhost:9200}
