
spring:
  data:
    mongodb:
      uri: ${DB_HOST:mongodb://AdminParas:admin1992@ec2-15-206-93-148.ap-south-1.compute.amazonaws.com/product}
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${ZOOKEEPER_HOST:localhost:9092}






