
spring:
  data:
    mongodb:
      uri: ${DB_HOST:mongodb://paras:admin1992@ec2-13-201-63-16.ap-south-1.compute.amazonaws.com/product}
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${ZOOKEEPER_HOST:3.7.253.26:9092}






