
spring:
  data:
    mongodb:
      uri: ${DB_HOST:mongodb://paras:admin@ec2-13-234-202-237.ap-south-1.compute.amazonaws.com/test}
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${ZOOKEEPER_HOST:13.235.244.23:9092}


elastic:
  search:
    host-name: ${ELASTIC_SEARCH_HOST:13.235.244.23:9200}
