
spring:
  data:
    mongodb:
      uri: ${DB_HOST:mongodb://paras:admin@ec2-13-127-211-30.ap-south-1.compute.amazonaws.com/test}
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${ZOOKEEPER_HOST:13.201.75.148:9092}


elastic:
  search:
    host-name: ${ELASTIC_SEARCH_HOST:13.201.75.148:9200}
